data:
  name: crossed_barrel

model:
  name: random_forest
  params:
    n_estimators: 100
    n_jobs: -1

train:
  n_seeds: 100
  n_initial: 2
  top_ratio: 0.05
  scaler: standard
  acquisition: LCB

